[package]
name = "reconcile"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
seo_steps = { path = "../../crates/seo_steps" }
infrastructure = { path = "../../crates/infrastructure" }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
sqlx = { workspace = true }
futures = { workspace = true }
uuid = { workspace = true }
