[package]
name = "cli_tools"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
use_cases = { path = "../../crates/use_cases" }
infrastructure = { path = "../../crates/infrastructure" }
primitives = { path = "../../crates/primitives" }
contracts = { path = "../../crates/contracts" }
anyhow = { workspace = true }
clap = { version = "4", features = ["derive"] }
serde_json = { workspace = true }
sqlx = { workspace = true }
prost = { workspace = true }
pulldown-cmark = "0.13.3"

hex = "0.4"
